### ISSUE TITLE
zigmod init doesn't work for me 

### ISSUE THREAD

**Issue by Sensenman1** [nektro/zigmod#100]
I am using a Windows 10 pro 64 os.
When I am following the https://nektro.github.io/zigmod/ Tutorial 
and i run the Command "zigmod init"
i get an Error Basicaly Stating that a no Funktion skript etc. hase been found with the name zigmod 
Error in German idk if it helps: 

zigmod : Die Benennung "zigmod" wurde nicht als Name eines Cmdlet, einer Funktion, einer Skriptdatei oder eines
ausführbaren Programms erkannt. Überprüfen Sie die Schreibweise des Namens, oder ob der Pfad korrekt ist (sofern
enthalten), und wiederholen Sie den Vorgang.
In Zeile:1 Zeichen:1
+ zigmod init
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (zigmod:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

I tried this with the Downloadable Exe and building from source
furthermore, i have run the Commands both from an Andmin and a non-Admin Powershell
Does anyone know what I should do?

**Comment by nektro** [comment]
an unqualified call to `zigmod init` will only work if the directory containing your copy of `zigmod.exe` is listed in your `PATH` environment variable

to fix this you should be able to either do that or also execute by relative path eg `.\path\to\zigmod.exe init`

**Comment by Sensenman1** [comment]
Ok Thank you very much .
