### ISSUE TITLE
compile zigmod from source missing `range` 

### ISSUE THREAD

**Issue by colemanbroad** [nektro/zigmod#16]
Hi, I ran into the following issue trying to compile zigmod from source with `zig-macos-x86_64-0.8.0-dev.2643+6426519e3`.

```
git clone https://github.com/nektro/zigmod --recursive
cd zigmod
zig build -Dbootstrap
./zig-out/bin/zigmod fetch
```
This finishes without complaints. But then I run into problems with `zig build`.
```
broaddus@myers-mac-28 zigmod % zig build
./src/cmd/zpm/tags.zig:6:15: error: unable to find 'range'
const range = @import("range").range;
              ^
./src/cmd/zpm/tags.zig:45:10: note: referenced here
    for (range(n)) |_| {
         ^
./src/cmd/zpm/tags.zig:32:5: note: referenced here
    try print_c_n(out, ' ', name_col_width - 4);
    ^
./src/cmd/zpm.zig:49:13: note: referenced here
            try cmd.execute(args[1..]);
            ^
./src/main.zig:34:13: note: referenced here
            try cmd.execute(args[1..]);
            ^
zigmod...The following command exited with error code 1:
```

So I looked around for the `range` module and it appears the download may have failed?

```
broaddus@myers-mac-28 zigmod % tree ./.zigmod/deps/v/http/aquila.red/1/nektro/range/
./.zigmod/deps/v/http/aquila.red/1/nektro/range/
└── v0.1.tar.gz
    └── d2f72fdd

2 directories, 0 files
```

Let me know if I'm being daft! And thanks for you work on zig[mod]!

**Comment by nektro** [comment]
Thanks for the report! I''ll look into trying to reproduce this and figuring out why it exited with no errors.

In the meantime, deleting the `.zigmod` folder and re-running `zigmod fetch` should work.

**Comment by colemanbroad** [comment]
OK thanks! Deleting `.zigmod` did the trick.
Now upon running `zig build` I get:

```zig
bash-3.2$ zig build
./src/cmd/license.zig:51:21: error: no member named 'entry' in struct 'std.array_hash_map.GetOrPutResult'
            map_item.entry.value = temp;
                    ^
./src/main.zig:34:13: note: referenced here
            try cmd.execute(args[1..]);
            ^
zigmod...The following command exited with error code 1:
```

**Comment by nektro** [comment]
this is because of a change made between the most recent master I used and the `0.8.0` release. Am working on a release as we speak.

**Comment by nektro** [comment]
The 0.8.0 fixes are now live here https://github.com/nektro/zigmod/releases/tag/v41 and here https://github.com/nektro/zigmod/commit/b9c825d2e3f09d4aa99ee80e4c898cd062c20dfc.

**Comment by colemanbroad** [comment]
fixed! thanks for all the hard work.
