### ISSUE TITLE
Add support for the `--version` flag or a `version` subcommand

### ISSUE THREAD

**Issue by xxami** [nektro/zigmod#18]
Another small feature request from me (sorry!)

The CLI currently doesn't behave conventionally, there's no `-v` or `version` command which is always a useful indicator of whether you've built the program correctly - and also no hint as to what any of the commands do outside of the documentation (ie. `zig help`)

It would also be nice to have positive affirmations about commands we perform such as `fetch` which currently doesn't output anything on success.

**Comment by nektro** [comment]
the version string is printed if you pass no arguments at all. but you're right, accepting `--version` or `version` would be useful.

for `fetch` the output is only empty if no fetching had to be done and the only work was generating `deps.zig`. success is indicated but the `0` exit code.
