### ISSUE TITLE
Publicize a minimum supported Zig version?

### ISSUE THREAD

**Issue by klardotsh** [nektro/zigmod#33]
Howdy! `zigmod` seems useful (and fairly simple, woohoo!), but as one who doesn't follow the nightlies of Zig, it looks like I'm in for a world of hurt trying to use it (or something's _actually_ broken and I'm just attributing it to Zig versions?)

```
./deps.zig:55:48: error: no member named 'path' in '[]const u8'
        .pkg = Pkg{ .name = "args", .path = .{ .path = dirs._xzxo5rnug8wj ++ "/args.zig" }, .dependencies = null },
                                               ^
./deps.zig:53:9: note: referenced here
    pub const _xzxo5rnug8wj = Package{
        ^
./deps.zig:59:26: note: referenced here
        .directory = dirs._6tp2yx5wnq30,
                         ^
./deps.zig:58:9: note: referenced here
    pub const _6tp2yx5wnq30 = Package{
        ^
/usr/lib/zig/std/meta.zig:367:68: note: referenced here
pub fn declarations(comptime T: type) []const TypeInfo.Declaration {
                                                                   ^
./deps.zig:12:38: note: referenced here
    inline for (std.meta.declarations(package_data)) |decl| {
```

Since I see a ton of references to zig-0.9 in the changelog, I went on a whim and assumed I needed to step back through the release history to eventually find something 0.8 compatible. I gave up somewhere around v60 and decided to just not manage dependency versions with a tool for now.

It'd be super helpful to have a line in the README to the effect of "here's the last version that supported the latest stable Zig compiler series" or so - similar to Gyro and a couple other tools I've seen.

Cheers!

**Comment by nektro** [comment]
the version in the readme is the minimum version as I tend to only update that line when i need to update zigmod code after something upstream broke it

**Comment by klardotsh** [comment]
Is there a plan to one day start tracking upstream's stable release channel in any awy? As it stands it looks like this pushes a "use Zig nightlies" requirement downstream which is a bit unfortunate (even if I understand _why_ it's currently that way).

**Comment by nektro** [comment]
i could potentially add a flag that prints release-compatible output if there's want for it. zigmod won't be around by the time zig reaches 1.0 so if its useful for people now im not super against it

generally speaking, zigmod also pushes for using the nightly version of libraries (which currently manifests itself in keeping up with the language changes) but its a pattern i'm personally going to continue going forward. in conjunction with [Stability Bit Versioning](https://www.youtube.com/watch?v=p_Rpkaoo8M8) of aforementioned libraries.

this is shown in the package index ive been working on https://aquila.red/ which implements this and does not support using semver

**Comment by klardotsh** [comment]
I wouldn't feel right asking you to do this for just me when I've found a workaround in the meantime - if other folks comment here, maybe it'll be worth reopening this discussion, but otherwise, I respect your stance (and appreciate the link to that talk - it's an intriguing way to look at versioning, so thank you!)

cheers!

**Comment by nektro** [comment]
Zigmod currently works with the 0.9.0 release

**Comment by chenrui333** [comment]
I am trying to get zigmod into homebrew-core, but I found it not working with the stable zig 0.10.1, should I hack the min zig version requirement to see how the build works?

**Comment by nektro** [comment]
zigmod HEAD is meant to work with zig master, https://github.com/nektro/zigmod/releases/tag/r84 will work with 0.10.1 though

**Comment by chenrui333** [comment]
I did a quick build but got the following failures

```
==> zig build --prefix /opt/homebrew/Cellar/zigmod/84 -Drelease-fast=true
thread 3266281 panic: Your Zig version v0.10.1 does not meet the minimum build requirement of v0.11.0-dev.193+eed82ca28
/private/tmp/zigmod-20230223-12812-j2zsn0/zigmod-r84/deps.zig:147:64: 0x10295340b in checkMinZig (build)
    if (current.order(min).compare(.lt)) @panic(exe.builder.fmt("Your Zig version v{} does not meet the minimum build requirement of v{}", .{current, min}));
                                                               ^
/private/tmp/zigmod-20230223-12812-j2zsn0/zigmod-r84/deps.zig:85:24: 0x10292b893 in addAllTo (build)
    checkMinZig(builtin.zig_version, exe);
                       ^
/private/tmp/zigmod-20230223-12812-j2zsn0/zigmod-r84/build.zig:24:18: 0x1028ee9b3 in build (build)
    deps.addAllTo(exe);
                 ^
/opt/homebrew/Cellar/zig/0.10.1/lib/zig/build_runner.zig:232:28: 0x1028dfb37 in runBuild (build)
        .Void => root.build(builder),
                           ^
/opt/homebrew/Cellar/zig/0.10.1/lib/zig/build_runner.zig:214:17: 0x1028dc53b in main (build)
    try runBuild(builder);
                ^
/opt/homebrew/Cellar/zig/0.10.1/lib/zig/std/start.zig:614:37: 0x1028dff0b in main (build)
            const result = root.main() catch |err| {
                                    ^
???:?:?: 0x199c83e4f in ??? (???)
???:?:?: 0x3208ffffffffffff in ??? (???)
```

**Comment by nektro** [comment]
https://github.com/nektro/zigmod/commit/8f01102e1f1cc122ee478528bcf8c11125aa018c will work

**Comment by chenrui333** [comment]
let me give that a try.

**Comment by chenrui333** [comment]
had some issues of accessing this resource

```
git https://gist.github.com/nektro/d468fea84f8217e4c26ee8fbeeea38cc commit-24c01e844396d18a90bbbfb91f8a5a12023e9379
```

**Comment by nektro** [comment]
that's #90

**Comment by nektro** [comment]
just pushed https://github.com/nektro/d468fea84f8217e4c26ee8fbeeea38cc as backup
