### ISSUE TITLE
aq fails on Windows

### ISSUE THREAD

**Issue by HugoFlorentino** [nektro/zigmod#36]
I was just trying to use this in a fresh project:

`zigmod aq add 1/jecolon/zigstr`

However, I got a `error.Unexpected: GetLastError(10093)` related to the app not calling WSAStartup.

**Comment by HugoFlorentino** [comment]
Apparently in `aq.zig` some check for Windows should be done before calling `zfetch.Request.init`.

In the specific case of Windows, zfetch's `network.init` needs to be called first, because it's the one calling `windows.WSAStartup`.

Also, `network.deinit` should probably be called after doing `req.deinit()` to keep things tidy, because it's the one calling `
`windows.WSACleanup()`.

**Comment by nektro** [comment]
https://github.com/MasterQ32/zig-network/blob/master/network.zig#L20-L30

**Comment by HugoFlorentino** [comment]
I have not found in zigmod's code the network socket initialization though.
