### ISSUE TITLE
fetch fails on Windows with "error: FileNotFound"

### ISSUE THREAD

**Issue by Earthnuker** [nektro/zigmod#41]
Hello everyone,

I'm using zig version `0.9.0` and zigmod version `v87.1995ca2 windows x86_64 gnu`. Trying to run `zigmod-x86_64-windows.exe fetch` in a clone of https://github.com/lun-4/obsidian2web at commit `cf75283` results in the following stack trace:

```
error: FileNotFound
/zig-linux-x86_64-0.9.0-dev.1815+20e19e75f/lib/std/heap.zig:150:9: 0x7ff6e4134735 in std.heap.CAllocator::std.heap.CAllocator.resize (zigmod-x86_64-windows.obj)
/zig-linux-x86_64-0.9.0-dev.1815+20e19e75f/lib/std/heap.zig:150:9: 0x7ff6e4134735 in std.heap.CAllocator::std.heap.CAllocator.resize (zigmod-x86_64-windows.obj)
/zig-linux-x86_64-0.9.0-dev.1815+20e19e75f/lib/std/heap.zig:150:9: 0x7ff6e4134735 in std.heap.CAllocator::std.heap.CAllocator.resize (zigmod-x86_64-windows.obj)
/zig-linux-x86_64-0.9.0-dev.1815+20e19e75f/lib/std/heap.zig:150:9: 0x7ff6e4134735 in std.heap.CAllocator::std.heap.CAllocator.resize (zigmod-x86_64-windows.obj)
/zig-linux-x86_64-0.9.0-dev.1815+20e19e75f/lib/std/heap.zig:150:9: 0x7ff6e4134735 in std.heap.CAllocator::std.heap.CAllocator.resize (zigmod-x86_64-windows.obj)
/zig-linux-x86_64-0.9.0-dev.1815+20e19e75f/lib/std/heap.zig:150:9: 0x7ff6e4134735 in std.heap.CAllocator::std.heap.CAllocator.resize (zigmod-x86_64-windows.obj)
/zig-linux-x86_64-0.9.0-dev.1815+20e19e75f/lib/std/heap.zig:150:9: 0x7ff6e4134735 in std.heap.CAllocator::std.heap.CAllocator.resize (zigmod-x86_64-windows.obj)
/zig-linux-x86_64-0.9.0-dev.1815+20e19e75f/lib/std/heap.zig:150:9: 0x7ff6e4134735 in std.heap.CAllocator::std.heap.CAllocator.resize (zigmod-x86_64-windows.obj)
/zig-linux-x86_64-0.9.0-dev.1815+20e19e75f/lib/std/heap.zig:150:9: 0x7ff6e4134735 in std.heap.CAllocator::std.heap.CAllocator.resize (zigmod-x86_64-windows.obj)
/zig-linux-x86_64-0.9.0-dev.1815+20e19e75f/lib/std/heap.zig:150:9: 0x7ff6e4134735 in std.heap.CAllocator::std.heap.CAllocator.resize (zigmod-x86_64-windows.obj)
/zig-linux-x86_64-0.9.0-dev.1815+20e19e75f/lib/std/fs.zig:1590:39: 0x7ff6e421325a in std.fs.Dir::std.fs.Dir.openDirAccessMaskW (zigmod-x86_64-windows.obj)
/zig-linux-x86_64-0.9.0-dev.1815+20e19e75f/lib/std/fs.zig:1529:9: 0x7ff6e414e5fd in std.fs.Dir::std.fs.Dir.openDirW (zigmod-x86_64-windows.obj)
/zig-linux-x86_64-0.9.0-dev.1815+20e19e75f/lib/std/fs.zig:1457:13: 0x7ff6e414d258 in std.fs.Dir::std.fs.Dir.openDir (zigmod-x86_64-windows.obj)
/home/circleci/zigmod/src/common.zig:218:79: 0x7ff6e4169cc9 in .zigmod.common.get_module_from_dep (zigmod-x86_64-windows.obj)
/home/circleci/zigmod/src/common.zig:41:13: 0x7ff6e4166a82 in .zigmod.common.collect_deps_deep (zigmod-x86_64-windows.obj)
/home/circleci/zigmod/src/cmd/fetch.zig:29:24: 0x7ff6e413d3fb in .zigmod.cmd.fetch.execute (zigmod-x86_64-windows.obj)
/home/circleci/zigmod/src/main.zig:54:13: 0x7ff6e4137c81 in main (zigmod-x86_64-windows.obj)
```

this seems to not be related to #38

(also the path to the debug symbols file seems to be hardcoded in the zigmod executable so i had to create `D:\home\circleci\zigmod\zig-cache\o\e7e9c8ee0d4909e4216ef5bee9f26177\` and move `zigmod-x86_64-windows.pdb` there, might be an issue for people without a D drive)

best regards,

Earthnuker

**Comment by Earthnuker** [comment]
Seems like merging #40 would fix this

**Comment by lun-4** [comment]
I can reproduce this issue (on `x86_64-linux.5.15.6...5.15.6-gnu.2.32`) with the fixes from #40.

One possible temporary fix I found to make `zigmod fetch` finish successfully is to manually create `.zigmod/deps` on the repository folder.

**Comment by lun-4** [comment]
This smells like #34. Tested with the aforementioned patch in `zigmod v87.1995ca2 linux x86_64 musl`.

**Comment by nektro** [comment]
what is the contents of your `zig.mod` ?

**Comment by yrashk** [comment]
It looks like I am having the same issue https://github.com/yrashk/zig-generator/runs/4638330127

My zig.mod: https://github.com/yrashk/zig-generator/blob/master/zig.mod

**Comment by nektro** [comment]
oh its *only* failing on windows, interesting. thanks for the run/file. additionally it seems to only be failing on the cross compiled version.

https://github.com/nektro/zigmod/runs/4630241454?check_suite_focus=true

GH Action is using natively compiled debug build, `actions-setup-zigmod` is downloading the `x86_64-windows-gnu` binary

**Comment by nektro** [comment]
oh wait @yrashk yours seems slightly different

**Comment by yrashk** [comment]
Here's the failing run with extra info https://github.com/yrashk/zig-generator/runs/4638493958

**Comment by yrashk** [comment]
I also tried to use a prebuilt version of zigmod on my Windows machine and it worked fine.

**Comment by yrashk** [comment]
I've tried pre-creating .zigmod/deps in CI, didn't help. Same error.

**Comment by lun-4** [comment]
I was doing some weird zig.mod shenanigans back on the mentioned issue, and was able to make it work after without changes on zigmod's side. @Earthnuker can you confirm?

**Comment by nektro** [comment]
yrashk's issue was fixed in another thread, will give @Earthnuker a little more time to confirm but this should otherwise be fixed now

**Comment by Earthnuker** [comment]
Hi, sorry for the late reply, yes with the latest of the repo `zigmod fetch` works fine on windows
