### ISSUE TITLE
using zigmod to set `exe.setLinkerScriptPath`

### ISSUE THREAD

**Issue by dannypsnl** [nektro/zigmod#45]
The beginning of the story is I'm wrapping [arduino lib](https://github.com/dannypsnl/avr-arduino-zig), I found correct build process requires `linker.ld` from the library, I fix this problem by copying the linker script from the library. But I wondering how can I avoid this, let zigmod add

```
exe.setLinkerScriptPath(.{ .path = "src/linker.ld" });
```

automatically?

**Comment by nektro** [comment]
what i would recommend at the moment is putting in the README

```zig
exe.setLinkerScriptPath(.{ .path = deps.dirs._8mdbh0zuneb1 ++ "/src/linker.ld" });
```

the `8mdbh0zuneb1` in the decl there is a truncation of the `id` field in your `zig.mod` manifest

**Comment by nektro** [comment]
atm the attributes Zigmod currently parses do not contain an analog to `setLinkerScriptPath` but i'm happy do discuss further if you'd like to work towards a more general solution if the above is not desirable

**Comment by dannypsnl** [comment]
> 

This approach has two problems

1. `dirs` is private in `deps.zig`, one has to export `dirs` manually, modifying a generated file is harmful
    ```
    /build.zig:19:44: error: 'dirs' is private
    ```
2. this is annoying for users

So, I think a general solution is needed. A simple approach immediately came up is we add a hook to let package access `LibExeObjStep`, then we get everything we need for the purpose. However, this approach may be toooooooo powerful, a problem I can find out now is according to [`setLinkerScriptPath`](https://github.com/ziglang/zig/blob/9f9f215305389c08a21730859982b68bf2681932/lib/std/build.zig#L1802-L1805), there has only one `.linker_script` field in `LibExeObjStep`, thus, two packages do this modification won't work together.

Another approach is we change `dirs` to **public**, then your suggestion would work normally.

I like the first one that helps users not need to do too much stuff, however, helping users keep their control is also important. Since the build script is powerful and the `id` of the package is stable, maybe we do a second one for now? What do you think?

**Comment by nektro** [comment]
I'm leaning towards the second for now, sorry for the field being private

the former has the problem you mentioned about having to deal with multiple packages setting it, as well as since its such a powerful feature I'd prolly want to warn the user even if a single project enabled it so that way they could confirm its a dependency they trust

**Comment by dannypsnl** [comment]
Yes, I think users should get warnings, even they have to allow one by one to let packages do these.
