### ISSUE TITLE
`zigmod ci` fails if there's no zigmod.lock

### ISSUE THREAD

**Issue by yrashk** [nektro/zigmod#55]
```
error: FileNotFound
```

Stack trace shows that it is from trying to open `zigmod.lock`. Should there be a better handling for this case?

**Comment by nektro** [comment]
that is by design. running `zigmod fetch` can generate a `zigmod.lock` for you

**Comment by yrashk** [comment]
Just didn't come to mind to run `zigmod fetch` on a project with no dependencies :)
