### ISSUE TITLE
Compilation fails on x86-64 Linux + Zig 0.10.0-dev.513+029844210

### ISSUE THREAD

**Issue by YellowApple** [nektro/zigmod#57]
I'm specifically on openSUSE Tumbleweed, with Zig compiled/installed via ASDF.

Full shell transcript of the steps to reproduce:

```
northrup@localhost:~/opt> zig version
0.10.0-dev.513+029844210
northrup@localhost:~/opt> git clone https://github.com/nektro/zigmod --recursive
Cloning into 'zigmod'...
remote: Enumerating objects: 3553, done.
remote: Counting objects: 100% (3553/3553), done.
remote: Compressing objects: 100% (1580/1580), done.
remote: Total 3553 (delta 2485), reused 2912 (delta 1866), pack-reused 0
Receiving objects: 100% (3553/3553), 488.84 KiB | 1.98 MiB/s, done.
Resolving deltas: 100% (2485/2485), done.
Submodule 'libs/yaml' (https://github.com/yaml/libyaml) registered for path 'libs/yaml'
Cloning into '/home/northrup/opt/zigmod/libs/yaml'...
remote: Enumerating objects: 2192, done.        
remote: Counting objects: 100% (23/23), done.        
remote: Compressing objects: 100% (18/18), done.        
remote: Total 2192 (delta 3), reused 16 (delta 2), pack-reused 2169        
Receiving objects: 100% (2192/2192), 1.43 MiB | 1.91 MiB/s, done.
Resolving deltas: 100% (1291/1291), done.
Submodule path 'libs/yaml': checked out 'acd6f6f014c25e46363e718381e0b35205df2d83'
northrup@localhost:~/opt> cd zigmod
northrup@localhost:~/opt/zigmod> zig build -Dbootstrap
./deps.zig:16:12: error: unable to evaluate constant expression
    inline for (std.meta.declarations(package_data)) |decl| {
           ^
```

Weirdly, it compiles fine if I revert to Zig 0.9.0 (though it's missing most subcommands when I actually run the resulting `zigmod` executable).

**Comment by nektro** [comment]
thanks for the report! I'll get this fixed up

**Comment by YellowApple** [comment]
Thanks, current `master` resolves this particular issue, and I was able to get the bootstrap `zigmod` compiled.

However, compiling the non-bootstrap `zigmod` fails (at least on Zig `master`, and probably also 0.9.0 but haven't tried it yet) due to what looks like [an upstream issue with zfetch](https://github.com/truemedian/zfetch/issues/10) (zig-uri made a breaking change, and zfetch hasn't been updated yet to account for it, so `zig build` fails for zigmod).

**Comment by nektro** [comment]
if you use `zigmod ci` instead of `zigmod fetch` It will pull in a working version of the dependencies that `zig build` will succeed for
