### ISSUE TITLE
Question: How to use the modules?

### ISSUE THREAD

**Issue by voroskoi** [nektro/zigmod#58]
I have tried to go through the tutorial to add a module, but I can not figure out how to use it.

So I have the `zig.mod` file, I download the dependency with `zigmod fetch`. I update `build.zig` to use `deps.zig`. These all seems to work fine.

But when I try to use the module:
```zig
const clap = @import("clap");
```

I got the following error: `error: unable to find 'clap'`. Obviously zig does not know where to find it, but every package I checked use them this way. I probably missing something here, but no idea where to look.

**Comment by nektro** [comment]
I mentioned this in a couple of threads but the more docs and references the better. this error is likely due to a mismatch of either `dependencies`/`root_dependencies` or an error in which `"root"`/`"your package"` point to the same file. I also have a longer writeup I did on discord below


![](https://cdn.discordapp.com/attachments/855801133061636136/928375070118793276/unknown.png)

**Comment by voroskoi** [comment]
I am sorry, I can not follow :-( The last 2 sentences especially, but I feel like my problem is something simpler than that as I am just trying to get the simplest version working.

So, I have created a test repo just for this: https://github.com/voroskoi/zigmod-test

I think I am doing the following:
I have created the `zig.mod` file for `zigmod-test`. As this file contains `name:` and `field:` and I have put `ziglyph` into `depends` it becomes a `C` in Your example. (But I do not really understand what is the difference between `root` and `A` in this case: I would think both root and A is zigmod-test.)

So what should I modify to make [this](https://github.com/voroskoi/zigmod-test/blob/0a292ffb7801092312754748d8d5361d1d87c89f/src/main.zig#L4) line work?

**Comment by nektro** [comment]
in `zig.mod`, remove `main:` and change deps to `root_dependencies:`, then rerun `zigmod fetch`

`main:` is only used if you're making a 3rd party library that others will import and represents the entry point of your package. it should never point to the same file as the one with `pub fn main` in it

**Comment by nektro** [comment]
alternatively, if you are making a package, add a separate `src/lib.zig` and change `main:` to point to that instead

then, `src/main.zig` will be able to do `@import("zigmod-test")` and `src/lib.zig` will be able to do `@import("ziglyph")`

**Comment by voroskoi** [comment]
I feel myself really stupid now.

I have tried [this](https://github.com/voroskoi/zigmod-test/commit/9014826c6b04630e881826f596855b41d8470c43) then [this](https://github.com/voroskoi/zigmod-test/commit/faa798cf7e9c04147b1cd50d9fae3c6aa92260da).

None of them works for me. Does it work for You?

**Comment by nektro** [comment]
are you running only `zig build` or `zig build test`?
for the latter you will have to also add `deps.addAllTo(main_tests);` in `build.zig`

**Comment by voroskoi** [comment]
Thank You, that did not cross my mind. I will send a PR to update `tutorial.md` with this information if You do not mind.
