### ISSUE TITLE
zigmod init not found?

### ISSUE THREAD

**Issue by donpdonp** [nektro/zigmod#59]
after building zigmod from source, I tried it in my zig project:

```
my_zig_proejct $ zigmod init
zigmod dev linux x86_64 gnu

The commands available are:
  - version
  - fetch
  - ci
my_zig_proejct $
```

**Comment by nektro** [comment]
following <https://github.com/nektro/zigmod#build-from-source>, if your command output looks like the following then that means you only performed the bootstrap step and must perform `zigmod fetch` + `zig build` an additional time to obtain a fully capable Zigmod

**Comment by donpdonp** [comment]
ah that was it thanks. Since all the steps are necessary to build zigmod, I think its easier to read if they're part of the same code block in the docs.
