### ISSUE TITLE
Feature Request: optionally fetch submodules for git dependencies

### ISSUE THREAD

**Issue by truemedian** [nektro/zigmod#6]
This would be helpful for libraries like `alexnask/iguanaTLS`, which include a submodule inside their source tree. But this should be optional, you don't always want to clone submodules.

**Comment by nektro** [comment]
> But this should be optional, you don't always want to clone submodules.

do you have a use case where this would be desired?

**Comment by truemedian** [comment]
Any library that uses both zigmod and submodules (for those who don't have zigmod), it would be a nice feature for it to be optional, but I could also see it being much easier to implement without.

**Comment by truemedian** [comment]
Closing this in favor of forcing developers to not do this, because it is a horrible idea.
