### ISSUE TITLE
Depency using git ssh URL

### ISSUE THREAD

**Issue by jacmoe** [nektro/zigmod#67]
I enjoy using Zigmod, but I have spent hours and hours today trying to fix build errors, until it dawned on me that perhaps using git ssh URLs would cause errors with Zig build.

I used these dependency URLs:

```
root_dependencies:
 - src: git git@github.com:jacmoe/zixelator.git
 - src: git git@github.com:jacmoe/zallegro.git
```

And Zigmod created  `.zigmod/deps/git/git@jacmoe.github.com:jacmoe/...`

Since I want to develop those deps myself, I went into the deps folders and worked on my Zig projects. But I got weird errors when trying to integrate with a C library ...  I was about to throw in the towel, but decided to simply copy the module I was working on into my home directory, and everything worked! :scream: :smiley_cat: 

So, I changed the funny path to `git_at_jacmoe.github.com_colon_jacmoe` , and it worked as well.

I want to use SSH instead of HTTPS because I am developing the modules at the moment, and it's very convenient to be able to just commit directly in the repositories.

Maybe Zigmod could handle this?

**Comment by nektro** [comment]
> I want to use SSH instead of HTTPS because I am developing the modules at the moment, and it's very convenient to be able to just commit directly in the repositories.

I use https for all my urls and use this same workflow. what error do you run into?

**Comment by jacmoe** [comment]
That Zig build doesn't know where `memory.h` is, or similar odd errors. I think the issue is that Zig passes the full path, with the `@` and the `:` character, to LLVM/clang, and confusion happens, maybe. Moving out of that path made all the odd errors vanish.

I could use https, but I prefer ssh.

**Comment by jacmoe** [comment]
Adding a remote, `origin_ssh`, using SSH, and setting it to be the default for push, works!

And Zigmod can still use the original https `origin` when fetching.

So, I guess I can have my cake, and eat it too :smile: 

I will close this issue because I guess people are not generally giving Zigmod ssh git urls. But, if they do, they can find the work-around here.
