### ISSUE TITLE
arqv/ini no longer exists

### ISSUE THREAD

**Issue by DivergentClouds** [nektro/zigmod#77]
When running `zigmod fetch` in the Zigmod source directory it attempts to download a number of dependencies. One of these (https://github.com/arqv/ini) is now a 404.

**Comment by nektro** [comment]
good catch. I have the code locally so if I can't find the place it might've moved to I will upload fork and change url

code is MIT Copyright (c) 2020 9hkke

**Comment by nektro** [comment]
user seems to be deleted from github and discord profile of author is now `Deleted User#0000` I will be indeed forking it
