### ISSUE TITLE
Monorepo support

### ISSUE THREAD

**Issue by postspectacular** [nektro/zigmod#86]
Is there're any support (existing or planned) for [monorepo setups](https://en.wikipedia.org/wiki/Monorepo), i.e. where a single git repo is hosting multiple packages, which may or may not also depend on each other? I've been studying the docs & YAML spec reference, but can't find anything relevant... I'm guessing this isn't a common setup in the Zig world, but it has many benefits when working on multiple, possibly loosely coupled libraries in parallel, also in terms of managing/automating  their releases and general maintenance...

Can you think of a way to support this usecase with the features available currently (maybe via some undocumented config setting)?

**Comment by nektro** [comment]
I myself use Zigmod in a monorepo as a consumer, but I've gone back and forth about supporting monorepos as a package provider. since Zigmod bases its package versions on git revisions, then the nature of the log of each package to be "cluttered" with the log of all other packages in the repo feels less than ideal. but it is a use case im interested in and `git log` accepts a refspec

**Comment by postspectacular** [comment]
Thanks for the quick response! I can understand your sentiment re cluttered commit logs, but even though this is unrelated to my original question now, I can only warmly recommend adopting the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) format, which helps to reduce said clutter and I've been successfully using it (for 5 years now) as main driver for managing & automating all versioning, changelogs, releases of ~175 projects (all in > 170k SLOC) in my [main monorepo](https://github.com/thi-ng/umbrella/)...

I will do some more research of how dependency resolution works in zigmod. In the meantime I've found that [gyro](https://github.com/mattnite/gyro) supports monorepo setups by placing a `gyro.zzz` file in the repo root, and allows to declare multiple packages within: [example](https://github.com/thi-ng/zig-thing/blob/main/gyro.zzz)
