### ISSUE TITLE
error: NoBuildZig

### ISSUE THREAD

**Issue by leap0x7b** [nektro/zigmod#87]
![Screenshot_20221226-100011_Termux.png](https://user-images.githubusercontent.com/76893443/209494310-ef1064ed-55cb-4c65-a262-748cd75151bc.png)

build.zig does exists so I don't know why it throws that

![Screenshot_20221226-100234_Termux.png](https://user-images.githubusercontent.com/76893443/209494364-43aaebd4-a463-4bc1-951a-03d99d168b5d.png)

**Comment by nektro** [comment]
https://github.com/managarm/lai is the one without a `build.zig` / `zigmod.yml`

in this case you have to define some attributes for it yourself

**Comment by leap0x7b** [comment]
Since it's a C library, I need to do something so I can link it with Zig

**Comment by nektro** [comment]
for that there are `c_source_files:`, `c_include_dirs:`, `c_source_flags:`

**Comment by nektro** [comment]
https://github.com/nektro/zig-zlib/blob/master/zig.mod is a nice example of this

**Comment by leap0x7b** [comment]
Thanks!
