### ISSUE TITLE
Make it easier to get the path to a dependency's folder

### ISSUE THREAD

**Issue by leroycep** [nektro/zigmod#9]
In `deps.zig` there is a list of paths to dependency folders, called `_paths`. However, `_paths` is an array which doesn't make it easy to go from package name to package path. In order to get the package path, you have to do one of the following:

1. Have the user copy the package ID into their `build.zig`, and then use that to locate the `_paths` index using `_ids` array
2. Get directory name from `deps.pkgs.pkg_name.path`. Caveat: this gives you the directory where the entry point file resides, and not the package's directory.

### Usecase

I am developing a [cross platform game library](https://github.com/leroycep/seizer) that allows the developer to target WASM. To make it easy to set up the WASM environment, a `.js` file is provided at `src/web/seizer.js`. Ideally the user would just add something like the following to their `build.zig`:

```zig
const install_seizerjs = b.addInstallFile(deps.pkgs.directory ++ "/src/web/seizer.js", "www/seizer.js");
// ...
build_web.dependOn(&install_seizerjs.step);
```

However, at the moment I don't feel that either solution is solid enough to recommend, so I will instead tell the user to manually copy `src/web/seizer.js` into their repository and then let the `build.zig` take it from there.

**Comment by nektro** [comment]
Thanks for the issue! This is definitely on the immediate roadmap.
