### ISSUE TITLE
Build fails on latest Zig

### ISSUE THREAD

**Issue by notramo** [nektro/zigmod#91]
@nektro, could you take a look at the build on latest nightly Zig?

**Comment by nektro** [comment]
currently blocked on https://github.com/marlersoft/zigwin32gen/issues/21

**Comment by orhun** [comment]
also hitting this for [zigmod](https://aur.archlinux.org/packages/zigmod) AUR package.

**Comment by nektro** [comment]
update will be pushed today

**Comment by notramo** [comment]
Any progress on this?
