### ISSUE TITLE
Compilation error in for loop

### ISSUE THREAD

**Issue by GPotoshin** [nektro/zigmod#95]
https://github.com/nektro/zigmod/blob/c04a957c4a5571a2e633e57db3e5c7160df04dc9/deps.zig#LL142C4-L142C4

```
zigmod/deps.zig:142:23: error: expected ')', found ','
        for (self.deps, 0..) |item, i| {
                      ^
```
Maybe they have changed something in a newer version of zig, but I got here an error. I suppose that now we write for loops without 0..
```zig
for (self.deps) |item, i| { ... }
```

**Comment by nektro** [comment]
what version of Zig are you using?

**Comment by GPotoshin** [comment]
It says 0.10.1
![Screenshot 2023-05-18 at 12 22 21](https://github.com/nektro/zigmod/assets/78864085/ac19892c-5389-4e96-b5ea-736fd586e36d)
