### ISSUE TITLE
34188 Errors when building from source with zig 0.11.0-dev.3971+6bc9c4f71

### ISSUE THREAD

**Issue by Sensenman1** [nektro/zigmod#97]
As mentioned when i build zigmod from source with Zig version 0.11.0-dev.3971+6bc9c4f71, i get about 34188 errors of those 33695 are error: expected 1 argument, found 2 . I am following the Tutorial (https://nektro.github.io/zigmod/)  Build Zigmod from source.                    I am very new to zig so i don't know anyway way i could fix this , is this a known Bug? I use a Windows machine with Windows 10 .           I attached a word file where i copied the entiere error messages.
[Microsoft Word-Dokument (neu) (2).docx](https://github.com/nektro/zigmod/files/12061007/Microsoft.Word-Dokument.neu.2.docx)

**Comment by nektro** [comment]
yeah this is known unfortunately, see the discussion in #96. at the latest it will be fixed with the tagged release of 0.11 which you can track the due date of here https://github.com/ziglang/zig/milestone/17

**Comment by Sensenman1** [comment]
ok thank you very much
